language: python
branches:
  only:
  - master
services:
- docker
install:
- chmod +x ./scripts/test.sh
- chmod +x ./scripts/publish.sh
script:
- if [[ $TRAVIS_EVENT_TYPE == "pull_request" ]] ; then ./scripts/test.sh ; fi
- if [[ $TRAVIS_EVENT_TYPE == "push" && $TRAVIS_BRANCH == "master" ]] ; then ./scripts/publish.sh
  ; fi
notifications:
  slack:
    secure: EPrBUhoPX8f1SqnRTGXQ6CkdK15LxumtghOftB9gAxHZYvi74hpwp8v5yKa+DAZ0mexYzIyzY4jl/g6TTTdvlg7yyDsioCL0VpiPXa4E3rWfJrNpMyxlDlLs9+pkTGxWmEsAFxKTw9uDwfQMsgi96Gvf1zgGX62E30KS+o2x3Ho8axvxbnCCZAhV+ACCKpex/p+fu1e+mmTjmkIr07TH4RenG5z/E+W8o2088WuPxytg7e1m1UIfxd6PbVUA89YEPHjlsBYVg7yXd9okIXhzaOscCw2VpOmbagcDvkXEmT+UmSHjyTUyDMCNRFcyMbgsWThJD9j7b3XdXVkY2c13W0zvXenLMZhIDVX7hmjFNVBSxZJ6j4Ii19U8+SgXkdSBz3JrJ3Ha8dexUZDuukIjYZj8qK8CRjqj14GZMb2KTpegC4Oudhr0DFJGHuwt33PB1jG+/HSt6HWV27oe7i06r5zH/JI3xv/rQUvvyUBfIHZ4HtUeo4IeK8RkaESsH2XwPyEEs0Pz7PtHi7wsC4ydPJtDkEUNvoY9o5XgbVjwrOCMnpcFAEJWTdkB54XTQpmGSw353MDhwqhFNn+ats6r0VRU2sZCeHaxttywLyMHxqH7t8ay/jY9CEzL99Iqulr7gSJyuTZ1pWCSDQnHrqmcMNZev3Jz/ybq/6iqT9yxUFU=
